### PR TITLE
Added support for dot net core app

### PR DESCRIPTION
**Pull request by guitarrapc**
Hi, I want this awesome library to be used in .NET Core App, AWS Lambda on .NET Core. I've added simple .xproj and project.json to cover this request.

Will you please check this?

I've made dummy NuGet Package for test it works on AWS Lambda. Plase see for a reference and I will remove it when you have merged.

https://www.nuget.org/packages/Chatwork.Service.Test/

Best,

### CODE REVIEW

**Comment by guitarrapc** [comment]
I've removed Test package from NuGet.

https://www.nuget.org/packages/Chatwork.Service.Test/

**Comment by tanaka-takayoshi** [comment]
I’ll release after I add some additional modification as v0.5.0, which is  corresponding to only .NET Standard

**Comment by tanaka-takayoshi** [comment]
releaed https://www.nuget.org/packages/Chatwork.Api/0.5.0

**Comment by guitarrapc** [comment]
寿司ゆき:gorgeous

**Pull request merged**
